### ISSUE TITLE
writelist sequence in fw_env.config does not work

### ISSUE THREAD

**Issue by Sperrus** [sbabic/libubootenv#32]
Hi, 

I have a fw_env.config file in YAML format on my device that looks like this:
```
uboot:
  size: 0x20000
  lockfile: /var/lock/fw_printenv.lock
  devices:
    - path: /dev/mmcblk0boot0
      offset: 0x1000000
    - path: /dev/mmcblk0boot1
      offset: 0x1000000

swupdate:
  size: 0x4000
  lockfile: /var/lock/swupdate.lock
  devices:
    - path: /dev/mmcblk0boot0
      offset: 0x1200000
    - path: /dev/mmcblk0boot1
      offset: 0x1200000
```

With this config fw_printenv works without problem and prints all variables.

As soon as I add a writelist sequence like this
```
  writelist:
    - var1:so
    - var2:so
    - var3:do
```

anywhere in the file I only get the output "Cannot initialize environment".

I am on version 0.3.5 773.
